name: Test Status Badge

on:
  push:
    branches: [ main, master ]
  workflow_run:
    workflows: ["Run Tests"]
    branches: [ main, master ]
    types:
      - completed

jobs:
  badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate test status badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: test-status.json
          label: tests
          message: ${{ github.event.workflow_run.conclusion == 'success' && 'passing' || 'failing' }}
          color: ${{ github.event.workflow_run.conclusion == 'success' && 'brightgreen' || 'red' }} 